version: "3"

services:
  master:
    image: jacintoarias/spark-cluster
    command: start-spark master
    hostname: master
    ports:
      - "7077:7077"
      - "8080:8080"
      - "4040:4040"
      - "50070:50070"
    volumes:
      - .:/home/spark

  worker:
    image: jacintoarias/spark-cluster
    command: start-spark worker master
    environment:
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 2g
    depends_on:
      - master